name: Lint & Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  dart-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: false
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

      - name: Generate App Localizations
        run: flutter gen-l10n

      - name: Get dependencies again after code-gen
        run: flutter pub get

      - name: Verify formatting
        run: dart format .

      - name: Analyze project source
        run: dart analyze --fatal-infos
