name: Build Android
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  release-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "17"
          cache: 'gradle'
          
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.10.5"
          channel: 'stable'
          cache: true
          
      # This fix ensures your NEW assets/images are used
      - name: Clean build cache
        run: flutter clean

      - name: Get dependencies
        run: flutter pub get
        
      - name: Build Release APK
        # We use --no-shrink for compatibility
        run: flutter build apk --release --no-shrink
        
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleWOL-Release-APK
          path: build/app/outputs/flutter-apk/app-release.apk
